config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users do
      resource :profile, only: :show
      resources :addresses
      resources :winners, only: [:show, :update]
      resources :shares,  only: [:show, :update]
      scope :orders, as: :orders do
        put 'cancel/:id', as: :cancel, to: 'orders#cancel'
      end
    end
    resources :invites
    resources :lottery
    resources :winner_experience, only: [:show, :index]
    resources :shop, only: :index do
      post :new_order
    end
    root to: 'home#index'
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :user_list, only: :index
      resources :items, except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, only: :index do
        put :cancel
      end
      resources :winners, only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, except: :show
      resources :orders, except: :show do
        put :submit, :pay ,:cancel
      end
      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only:  [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :invite_list, only: :index
      resources :news_tickers, except: :show
      resources :banners, except: :show
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :bets
  has_many :orders

  validates_uniqueness_of :username
  validates :phone, phone: {allow_blank: true}
  belongs_to :parent, class_name: "User", optional: true, counter_cache: :children_members
  has_many :children, class_name: "User", foreign_key: 'parent_id'

  mount_uploader :image, ImageUploader

  def client?
    role == 'client'
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_own_address, only: [:destroy, :edit, :update]

  def index
    @addresses = current_user.addresses.includes(:region, :province, :city, :barangay)
  end

  def new
    @address= Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      flash[:notice] = "Successfully Created"
      redirect_to users_addresses_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = "Successfully Updated"
      redirect_to users_addresses_path
    else
      render :edit
    end
  end

  def destroy
    if @address.destroy
      flash[:notice] = "Successfully Deleted"
    else
      flash[:alert] = @address.errors.full_messages.join(', ')
    end
    redirect_to users_addresses_path
  end

  private

  def set_own_address
    @address = current_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:name, :phone_number, :street_address, :genre, :region_id, :province_id, :city_id, :barangay_id, :remark, :is_default)
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :set_order, only: :cancel

  def cancel
    if @order.cancel!
      flash[:notice] = "Successfully Cancelled"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to users_profile_path(report: 'order')
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @orders = Order.where(user: current_user) if params[:report] == 'order' || params[:report].blank?
    @bets = Bet.includes(:item).where(user: current_user) if params[:report] == 'bet'
    @invitations = User.where(parent: current_user) if params[:report] == 'invite'
    @winners = Winner.includes(:item, :bet).where(user: current_user) if params[:report] == 'winner'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @promoter = User.find_by_email(cookies[:promoter])&.id
    super
    unless cookies[:promoter]
      cookies[:promoter] = params[:promoter]
    end
  end

  def create
    params[:user][:parent_id] = User.find_by_email(cookies[:promoter])&.id
    super
  end

  def edit; end

  def update
    if params[:user][:current_password].present?
      if current_user.update_with_password(password_params)
        flash[:notice]= "Updated successfully!"
        sign_in @user, :bypass => true
        redirect_to edit_user_registration_path
      else
        flash[:alert] = 'Oh No! Something Went Wrong in password update field, Please Try Again.'
        render :edit
      end
    else
      if current_user.update(userinfo_params)
        flash[:notice]="Updated successfully!"
        redirect_to edit_user_registration_path
      else
        flash[:alert] = 'Oh No! Something Went Wrong, Please Try Again.'
        render :edit
      end
    end
  end

  private

  def userinfo_params
    params.require(:user).permit(:email, :username, :phone, :image)
  end

  def password_params
    params.require(:user).permit(:password,:password_confirmation, :current_password, :email, :username, :phone, :image)
  end

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :parent_id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    super
  end

  def create
    user = User.find_for_authentication(email: params[:user][:email])
    if user&.admin? && user&.valid_password?(params[:user][:password])
      flash[:notice] = "You do not have permission"
      redirect_to action: :new
    else
      super
    end
  end
end

app/controllers/users/shares_controller.rb
class Users::SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner

  def show; end

  def update
    if @winner.update(winner_params) && @winner.share!
      flash[:notice] = "Successfully Shared!"
      redirect_to users_profile_path(report: 'winner')
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
      render :show
    end
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).delivered.find(params[:id])
  end

  def winner_params
    params.require(:winner).permit(:comment, :picture)
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.claim! && @winner.update(address: @address)
      flash[:notice] = "Successfully Claimed!"
    else
      flash[:alert] = "Failed to Claim!"
    end
    redirect_to users_profile_path(report: 'winner')
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).find(params[:id])
  end

  def set_address
    @address = Address.where(user: current_user).find(params[:winner][:address])
  end
end

app/views/users/shared/_banner.html.erb
<style>
    .marquee-container {
        width: 100%;
        overflow: hidden;
        white-space: nowrap;
    }

    .marquee {
        padding-left: 100%;
        display: inline-block;
        animation: marquee 7s linear infinite;
        animation-play-state: running;
        font-size: 20px;
    }

    .marquee.paused, .marquee-container:hover .marquee {
        animation-play-state: paused;
    }

    @keyframes marquee {
        0% {
            transform: translateX(0);
        }
        100% {
            transform: translateX(-100%);
        }
    }

    .carousel-item img {
        object-fit: cover;
        object-position: 50% 50%;
    }
</style>
<div class="container" style="width: 1220px">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <% banners.count.times do |index| %>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></button>
      <% end %>
    </div>
    <div class="carousel-inner" style="max-height: 50vh; background-color: black;">
      <% banners.each_with_index do |banner, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag banner.preview.url, alt: 'avatar', class: "d-flex w-100" if banner.preview? %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<section class=" text-light bg-dark" style="height: 5vh;">
  <div class="container" style="width: 1220px">
    <div class="marquee-container">
      <div class="marquee paused mt-1">
        <% news_ticker.each do |news_ticker| %>
          <span><%= news_ticker.content %></span>
        <% end %>
      </div>
    </div>
  </div>
</section>

<script>
    $(document).ready(function () {
        let key = 0;
        const marquee = $('.marquee');
        $('.marquee span').hide()
        $(".marquee").children().eq(key).show()

        marquee.on('animationiteration', () => {
            key++;
            if (($(".marquee").children().length) == key) key = 0;
            $('.marquee span').hide()
            $(".marquee").children().eq(key).show();
        });

        marquee.removeClass('paused');
    })
</script>

app/views/users/shared/_layout.html.erb
<style>
    .label {
        display: block;
        color: black;
        font-size: 12px;
        margin: 0;
        padding: 0;
        text-align: center;
    }
</style>
<% if current_user %>
  <nav class="navbar bg-info fixed-top">
    <div class="container-fluid" style="max-width: 1220px">
      <%= link_to root_path, class: 'img-fluid' do %>
        <img alt="logo" src="/logo.png" style="width: 19vw; max-width: 150px">
      <% end %>
      <ul class="nav ms-auto">
        <li class="nav-item m-auto">
          <div class="px-1" style="background-color: #000; border-radius: 5px; padding: 2px;">
            <%= link_to shop_index_path, class: 'text-decoration-none text-light bold', style: 'font-weight: bolder' do %>
              <%= current_user.coins %>
              <img alt="logo" src="/coin.svg" style="width: 20px; margin-left: 3px; margin-bottom: 3px">
              </div>
            <% end %>
            </li>
        <li class="nav-item m-auto">
          <a class="nav-link text-white" href="#">Claim </a>
        </li>
        <li class="nav-item m-auto">
          <%= link_to class:'img-fluid' do %>
            <img alt="logo" src="/globe.svg" style="width: 30px; margin-right: 12px">
          <% end %>
        </li>
      </ul>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <button type="button" class="btn-close ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <%= image_tag current_user.image.thumb.url, class: "d-flex justify-content-start rounded-circle mb-2", style: 'width: 50px' if current_user.image? %>
            <li class="nav-item">
              <%= "#{"Username: "}#{current_user.username}" %>
            </li>
            <li class="nav-item">
              <%= "#{"Email: "}#{current_user.email}" %>
            </li>
            <li class="nav-item">
              <%= "#{"Coins: "}#{current_user.coins}" %>
            </li>
            <li class="nav-item">
              <button class="btn btn-primary form-control">Cash In Now</button>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact Us</a>
            </li>
            <li class="nav-item">
              <a><%= link_to "Profile", users_profile_path, class: "nav-link text-black" %></a>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link text-black" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
    <ul class="nav mx-auto">
      <li class="nav-item px-4 px-lg-5">
        <%= link_to winner_experience_index_path, class: 'img-fluid' do %>
          <img alt="logo" src="/share.svg" style="width: 22px; margin-left: 4px">
        <% end %>
        <span class="label">Share</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to invites_path, class: 'img-fluid' do %>
          <img alt="logo" src="/infinity.svg" style="width: 22px; margin-left: 4px">
        <% end %>
        <span class="label">Invite</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to lottery_index_path, class: 'img-fluid' do %>
          <img alt="logo" src="/box2-heart.svg" style="width: 22px; margin-left: 8px">
        <% end %>
        <span class="label">Lottery</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to shop_index_path, class: 'img-fluid' do %>
          <img alt="logo" src="/shop.svg" style="width: 22px; margin-left: 3px">
        <% end %>
        <span class="label">Shop</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to users_profile_path, class: 'img-fluid' do %>
          <img alt="logo" src="/person.svg" style="width: 22px; margin-right: 1px">
        <% end %>
        <span class="label">Me</span>
      </li>
    </ul>
  </nav>
<% else %>
  <nav class="navbar bg-info fixed-top">
    <div class="container-fluid" style="max-width: 1220px">
      <%= link_to root_path, class: 'img-fluid' do %>
        <img alt="logo" src="/logo.png" style="width: 19vw; max-width: 150px">
      <% end %>
      <ul class="nav">
        <li class="nav-item px-2">
          <%= link_to "Login", new_user_session_path, class: "btn btn-dark btn-sm mt-1" %>
        </li>
        <li class="nav-item px-2">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-dark btn-sm mt-1" %>
        </li>
        <li class="nav-item px-2 mt-1">
          <%= link_to class: 'img-fluid' do %>
            <img alt="logo" src="/globe.svg" style="width: 30px; margin-right: 5px">
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
      <button type="button" class="btn-close ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" style="font-family:'Baloo 2', cursive;">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        <p>
        <li class="nav-item me-auto" href="#">Contact Us</li>
        </p>
        <p>
        <li class="nav-item me-auto" href="#">Facebook</li>
        </p>
      </ul>
    </div>
  </div>
  <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
    <ul class="nav mx-auto">
      <li class="nav-item px-4 px-lg-5">
        <%= link_to winner_experience_index_path class: 'img-fluid' do %>
          <img alt="logo" src="/share.svg" style="width: 22px; margin-left: 4px">
        <% end %>
        <span class="label">Share</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to invites_path, class: 'img-fluid' do %>
          <img alt="logo" src="/infinity.svg" style="width: 22px; margin-left: 4px">
        <% end %>
        <span class="label">Invite</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to lottery_index_path, class: 'img-fluid' do %>
          <img alt="logo" src="/box2-heart.svg" style="width: 22px; margin-left: 8px">
        <% end %>
        <span class="label">Lottery</span>
      </li>
      <li class="nav-item px-4 px-lg-5">
        <%= link_to shop_index_path, class: 'img-fluid' do %>
          <img alt="logo" src="/shop.svg" style="width: 22px; margin-left: 3px">
        <% end %>
        <span class="label">Shop</span>
      </li>
    </ul>
  </nav>
<% end %>