config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users do
      resource :profile, only: :show
      resources :addresses
      resources :winners, only: [:show, :update]
      resources :shares,  only: [:show, :update]
      scope :orders, as: :orders do
        put 'cancel/:id', as: :cancel, to: 'orders#cancel'
      end
    end
    resources :invites
    resources :lottery
    resources :winner_experience, only: [:show, :index]
    resources :shop, only: :index do
      post :new_order
    end
    root to: 'home#index'
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :user_list, only: :index
      resources :items, except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, only: :index do
        put :cancel
      end
      resources :winners, only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, except: :show
      resources :orders, except: :show do
        put :submit, :pay ,:cancel
      end
      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only:  [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :invite_list, only: :index
      resources :news_tickers, except: :show
      resources :banners, except: :show
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :remarks, presence: true, if: :specific_genre
  validates :amount, :coin, numericality: { greater_than: 0 }, if: :deposit?
  validates :amount, numericality: { greater_than_or_equal: 0 }, unless: :deposit?
  enum genre: [:deposit, :increase, :deduct, :bonus, :share]

  belongs_to :user
  belongs_to :offer, optional: true

  after_create :generate_serial_number

  include AASM
  aasm column: :state do
    state :pending, initial: true
    state :submitted, :cancelled, :paid

    event :submit do
      transitions from: :pending, to: :submitted
    end

    event :pay, after: :update_coins_if_to_pay do
      transitions from: :submitted, to: :paid, guard: :deposit?, after: :update_deposit_if_to_pay
      transitions from: :pending, to: :paid, guard: :check_coin_if_to_pay
    end

    event :cancel do
      transitions from: [:pending, :submitted], to: :cancelled
      transitions from: :paid, to: :cancelled, guard: :check_coin_if_to_cancel, after: [:update_coins_if_to_cancel, :update_deposit_if_to_cancel]
    end
  end

  def update_coins_if_to_pay
    if !deduct?
      user.update(coins: user.coins + coin)
    else
      user.update(coins: user.coins - coin)
    end
  end

  def update_deposit_if_to_pay
    if deposit?
      user.update(total_deposit: user.total_deposit + amount)
    end
  end

  def update_coins_if_to_cancel
    if !deduct?
      user.update(coins: user.coins - coin)
    else
      user.update(coins: user.coins + coin)
    end
  end

  def update_deposit_if_to_cancel
    if deposit?
      user.update(total_deposit: user.total_deposit - amount)
    end
  end

  def check_coin_if_to_cancel
    return true if deduct?
    if (user.coins >= coin)
      true
    else
      errors.add(:base, "Don't have enough coins")
      false
    end
  end

  def check_coin_if_to_pay
    return true unless deduct?
    if (user.coins >= coin)
      true
    else
      errors.add(:base, "Don't have enough coins")
      false
    end
  end

  def specific_genre
    increase? || deduct? || bonus?
  end

  def generate_serial_number
    ActiveRecord::Base.connection.execute("UPDATE `orders` SET `orders`.`serial_number` = CONCAT(DATE_FORMAT(CONVERT_TZ(orders.created_at, '+00:00', '+8:00'), '%y%m%d'),'-',#{id},'-',#{user.id},'-',
                                                    (SELECT LPAD(count(*), 4, 0)
                                                     FROM `orders` where `orders`.`user_id` = #{user.id}))
                                                     WHERE orders.id = #{id}")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, except: :index

  def index
    @orders = Order.includes(:user, :offer)
    @total_coin = @orders.map(&:coin).sum
    @total_amount = @orders.map(&:amount).sum
    @orders = @orders.where(serial_number: params[:serial_number]) if params[:serial_number].present?
    @orders = @orders.where(user: { email: params[:email] }) if params[:email].present?
    @orders = @orders.where(genre: params[:genre]) if params[:genre].present?
    @orders = @orders.where(state: params[:state]) if params[:state].present?
    @orders = @orders.where(offer: params[:offer]) if params[:offer].present?
    @orders = @orders.where(created_at: params[:start_date].to_datetime..params[:end_date].to_datetime) if params[:start_date].present? && params[:end_date].present?
    @sub_total_coin = @orders.map(&:coin).sum
    @sub_total_amount = @orders.map(&:amount).sum
  end

  def submit
    if @order.submit!
      flash[:notice] = "Successfully Submitted"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to admin_orders_path
  end

  def pay
    if @order.pay!
      flash[:notice] = "Successfully Paid"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to admin_orders_path
  end

  def cancel
    if @order.cancel!
      flash[:notice] = "Successfully Cancelled"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to admin_orders_path
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :set_order, only: :cancel

  def cancel
    if @order.cancel!
      flash[:notice] = "Successfully Cancelled"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to users_profile_path(report: 'order')
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/views/admin/orders/index.html.erb
<div class="center w-75" style="margin: 50px auto">
  <div class="main">
    <%= render 'errors/flash_error' %>
    <div class="card shadow mb-3">
      <div class="card-body">
        <%= form_tag({ url: admin_orders_path }, { method: :get }) do %>
          <div class="row">
            <div class="col-3">
              <%= label_tag :serial_number %>
              <%= text_field_tag :serial_number, params[:serial_number], class: "form-control" %>
            </div>
            <div class="col-3">
              <%= label_tag :email %>
              <%= text_field_tag :email, params[:email], class: "form-control" %>
            </div>
            <div class="col-3">
              <%= label_tag :genre %>
              <%= select_tag :genre, options_for_select(Order.genres.keys.map { |key| [key.humanize, key] }, params[:genre]), { prompt: 'Genre', class: "form-control form-select" } %>
            </div>
            <div class="col-3">
              <%= label_tag :state %>
              <%= select_tag :state, options_for_select(Order.aasm.states.map(&:name)), { prompt: 'State', class: "form-control form-select" } %>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-4">
              <%= label_tag :offer %>
              <%= select_tag :offer, options_for_select(Offer.pluck(:name, :id), params[:offer]), { prompt: 'Select Offer', class: "form-control form-select" } %>
            </div>
            <div class="col-4">
              <%= label_tag :created_at %>
              <div class="input-group">
                <span class="input-group-text">From</span>
                <%= datetime_field_tag :start_date, params[:start_date], class: "form-control" %>
              </div>
            </div>
            <div class="col-4 mt-auto">
              <div class="input-group">
                <span class="input-group-text">To</span>
                <%= datetime_field_tag :end_date, params[:end_date], class: "form-control" %>
              </div>
            </div>
          </div>
          <%= submit_tag :Search, class: "btn btn-warning mt-3" %>
          <%= link_to 'Reset', admin_orders_path, class: "btn btn-info mt-3" %>
        <% end %>
      </div>
    </div>
    <table class="table table-dark table-striped text-center fs-6">
      <thead class="table-active">
      <tr>
        <th></th>
        <th scope="col">Subtotal</th>
        <th scope="col">Total</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th>Coin</th>
        <td><%= @sub_total_coin %></td>
        <td><%= @total_coin %></td>
      </tr>
      <tr>
        <th>Amount</th>
        <td><%= @sub_total_amount %></td>
        <td><%= @total_amount %></td>
      </tr>
      </tbody>
    </table>
    <table class="table table-dark table-striped text-center fs-6">
      <thead class="table-active">
      <tr>
        <th colspan="8">Order List</th>
      </tr>
      <tr>
        <th scope="col">Serial Number</th>
        <th scope="col">Email</th>
        <th scope="col">State</th>
        <th scope="col">Genre</th>
        <th scope="col">Offer Name</th>
        <th scope="col">Amount</th>
        <th scope="col">Date Created</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <% if @orders.blank? %>
        <td colspan="8">No Orders Found</td>
      <% end %>
      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.serial_number %></td>
          <td><%= order.user.email %></td>
          <td><%= order.state %></td>
          <td><%= order.genre %></td>
          <td><%= order.offer&.name %></td>
          <td><%= order.offer&.amount %></td>
          <td><%= order.created_at %></td>
          <td><%= link_to 'Submit', admin_order_submit_path(order), class: 'btn btn-primary col-8', method: :put, data: { confirm: 'Are you sure?' } if order.may_submit? %>
          <%= link_to 'Pay', admin_order_pay_path(order), class: 'btn btn-warning col-8', method: :put, data: { confirm: 'Are you sure?' } if order.may_pay? %>
          <%= link_to 'Cancel', admin_order_cancel_path(order), class: 'btn btn-danger col-8 mt-3', method: :put, data: { confirm: 'Are you sure?' } if order.may_cancel? %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>