config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users do
      resource :profile, only: :show
      resources :addresses
      resources :winners, only: [:show, :update]
      resources :shares,  only: [:show, :update]
      scope :orders, as: :orders do
        put 'cancel/:id', as: :cancel, to: 'orders#cancel'
      end
    end
    resources :invites
    resources :lottery
    resources :winner_experience, only: [:show, :index]
    resources :shop, only: :index do
      post :new_order
    end
    root to: 'home#index'
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :user_list, only: :index
      resources :items, except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, only: :index do
        put :cancel
      end
      resources :winners, only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, except: :show
      resources :orders, except: :show do
        put :submit, :pay ,:cancel
      end
      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only:  [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :invite_list, only: :index
      resources :news_tickers, except: :show
      resources :banners, except: :show
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @winners = Winner.published.limit(5).order(id: :desc)
    @items = Item.active.starting.limit(8)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render '/users/shared/banner' %>
<%= render 'errors/flash_error' %>
<div class="container" style="margin-bottom: 100px; max-width: 1220px">
  <h4 class="py-2">Winners Feedback</h4>
  <div class="row">
    <% @winners.each do |winner| %>
      <div class="col">
        <div class="card shadow">
          <div class="body">
            <div class="w-100 overflow-hidden" style="aspect-ratio: 1 / 1">
              <%= link_to (image_tag winner.picture.url, alt: 'winner', class: "d-flex w-100" if winner.picture?), winner_experience_path(winner) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @winners.size == 5 %>
      <div class="col">
        <%= link_to winner_experience_index_path, class: 'text-decoration-none text-dark' do %>
          <div class="card shadow">
            <div style="aspect-ratio: 1 / 1; display: flex; align-items: center; justify-content: center;">More...</div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <h4 class="py-2">Coming Soon</h4>
    <% @items.each do |item| %>
      <div class="col-6 col-md-4 col-lg-3">
        <div class="card shadow border-none mb-3 overflow-hidden" style="max-height: 250px; height:20vw; min-height: 220px">
          <div class="overflow-hidden">
            <%= link_to (image_tag item.image.url, alt: 'winner', class: 'card-img-top img-responsive' if item.image?), lottery_path(item) %>
          </div>
          <div class="card-footer flex-column mt-auto">
            <h6 class="text-start"><%= item.name %></h6>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if @items.size == 8 %>
    <div class="float-end"><%= link_to 'More...', lottery_index_path, class: 'text-decoration-none text-dark' %></div>
  <% end %>
</div>
<%= render "users/shared/layout" %>