config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users do
      resource :profile, only: :show
      resources :addresses
      resources :winners, only: [:show, :update]
      resources :shares,  only: [:show, :update]
      scope :orders, as: :orders do
        put 'cancel/:id', as: :cancel, to: 'orders#cancel'
      end
    end
    resources :invites
    resources :lottery
    resources :winner_experience, only: [:show, :index]
    resources :shop, only: :index do
      post :new_order
    end
    root to: 'home#index'
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :user_list, only: :index
      resources :items, except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, only: :index do
        put :cancel
      end
      resources :winners, only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, except: :show
      resources :orders, except: :show do
        put :submit, :pay ,:cancel
      end
      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only:  [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :invite_list, only: :index
      resources :news_tickers, except: :show
      resources :banners, except: :show
    end
  end
end

app/models/winner.rb
class Winner < ApplicationRecord
  validates :picture, :comment, presence: true, if: :shared?
  belongs_to :item
  belongs_to :bet
  belongs_to :user
  belongs_to :address, optional: true
  belongs_to :admin, class_name: 'User', optional: true

  mount_uploader :picture, ImageUploader

  include AASM
  aasm column: :state do
    state :won, initial: true
    state :claimed, :submitted, :paid, :shipped, :delivered, :shared, :published, :remove_published

    event :claim do
      transitions from: :won, to: :claimed
    end

    event :submit do
      transitions from: :claimed, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :share do
      transitions from: :delivered, to: :shared
    end

    event :publish do
      transitions from: [:shared,:remove_published], to: :published
    end

    event :remove_publish do
      transitions from: :published, to: :remove_published
    end
  end
end

app/controllers/admin/winners_controller.rb
class Admin::WinnersController < AdminController
  before_action :set_winner, except: :index

  def index
    @winners = Winner.includes(:user, :item, :bet, :address)
    @winners = @winners.where(bet: { serial_number: params[:serial_number] }) if params[:serial_number].present?
    @winners = @winners.where(user: { email: params[:email] }) if params[:email].present?
    @winners = @winners.where(item: { name: params[:product_name] }) if params[:product_name].present?
    @winners = @winners.where(state: params[:state]) if params[:state].present?
    @winners = @winners.where(created_at: params[:start_date].to_datetime..params[:end_date].to_datetime) if params[:start_date].present? && params[:end_date].present?
  end

  def submit
    if @winner.submit!
      flash[:notice] = "Successfully Submit"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def pay
    if @winner.pay!
      flash[:notice] = "Successfully Pay"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def ship
    if @winner.ship!
      flash[:notice] = "Successfully Ship"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def deliver
    if @winner.deliver!
      flash[:notice] = "Successfully Deliver"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def publish
    if @winner.publish!
      flash[:notice] = "Successfully Publish"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def remove_publish
    if @winner.remove_publish!
      flash[:notice] = "Successfully Remove Publish"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  private

  def set_winner
    @winner = Winner.find(params[:winner_id])
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.claim! && @winner.update(address: @address)
      flash[:notice] = "Successfully Claimed!"
    else
      flash[:alert] = "Failed to Claim!"
    end
    redirect_to users_profile_path(report: 'winner')
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).find(params[:id])
  end

  def set_address
    @address = Address.where(user: current_user).find(params[:winner][:address])
  end
end

app/views/admin/winners/index.html.erb
<div class="center w-75" style="margin: 50px auto">
  <div class="main">
    <%= render 'errors/flash_error' %>
    <div class="card shadow mb-3">
      <div class="card-body">
        <%= form_tag({ url: admin_winners_path }, { method: :get }) do %>
          <div class="row">
            <div class="col-4">
              <%= label_tag :serial_number %>
              <%= text_field_tag :serial_number, params[:serial_number], class: "form-control" %>
            </div>
            <div class="col-4">
              <%= label_tag :email %>
              <%= text_field_tag :email, params[:email], class: "form-control" %>
            </div>
            <div class="col-4">
              <%= label_tag :state %>
              <%= select_tag :state, options_for_select(Winner.aasm.states.map(&:name), params[:state]), { prompt: 'state', class:"form-control form-select"}%>
            </div>
          </div>
          <div class="row mt-2">
            <%= label_tag :created_at %>
            <div class="col-6">
              <div class="input-group">
                <span class="input-group-text">From</span>
                <%= datetime_field_tag :start_date, params[:start_date], class: "form-control"%>
              </div>
            </div>
            <div class="col-6">
              <div class="input-group">
                <span class="input-group-text">To</span>
                <%= datetime_field_tag :end_date, params[:end_date], class: "form-control" %>
              </div>
            </div>
          </div>
          <%= submit_tag :Search, class: "btn btn-warning mt-3" %>
          <%= link_to 'Reset', admin_winners_path, class: "btn btn-info mt-3" %>
        <% end %>
      </div>
    </div>
    <table class="table table-dark table-striped text-center fs-6">
      <thead class="table-active">
      <tr>
        <th colspan="6">Winner List</th>
      </tr>
      <tr class="table-active">
        <th scope="col">Serial Number</th>
        <th scope="col">Email</th>
        <th scope="col">State</th>
        <th scope="col">Address</th>
        <th scope="col">Date Created</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <% if @winners.blank? %>
        <td colspan="6">No Winner Found</td>
      <% end %>
      <tbody>
      <% @winners.each do |winner| %>
        <tr>
          <td><%= winner.bet&.serial_number %></td>
          <td><%= winner.user.email %></td>
          <td><%= winner.state %></td>
          <td><%= concat_address(winner.user.addresses.find_by_is_default(true)) %></td>
          <td><%= winner.created_at %></td>
          <td><%= link_to 'Submit', admin_winner_submit_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_submit? %>
            <%= link_to 'Pay', admin_winner_pay_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_pay? %>
            <%= link_to 'Ship', admin_winner_ship_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_ship? %>
            <%= link_to 'Deliver', admin_winner_deliver_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_deliver? %>
            <%= link_to 'Publish', admin_winner_publish_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_publish? %>
            <%= link_to 'Remove Publish', admin_winner_remove_publish_path(winner), class: 'btn btn-primary col-12', method: :put, data: {confirm: 'Are you sure?'} if winner.may_remove_publish? %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>